version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Generic-variation-analysis-on-WGS-PE-data.ga
  subclass: Galaxy
  testParameterFiles:
  - /Generic-variation-analysis-on-WGS-PE-data-tests.yml
